[package]
name = "squad"
version = "0.1.0"
edition = "2021"

[dependencies]
float-ord = "0.3.2"
mint = "0.5.9"
treeculler = "0.2.0"

[dev-dependencies]
criterion = "0.3.5"
parry3d = "0.8.0"
rand = "0.8.5"

[[bench]]
name = "squad_goals"
harness = false
